### ISSUE TITLE
Extending service with port and auth

### ISSUE THREAD

**Issue by BlagoCuljak** [prjseal/Portfolio-Starter-Kit-fo-Umbraco#7]
Right now, when sending emails, the server needs to be able to take email for sending without authentication, which can be used for spam.

Extend the service with authentication from appsetings.json port, username and password.

**Comment by prjseal** [comment]
Hi
I'm not sure what you are saying is wrong here. Currently it uses IEmailSender to send the message which is a wrapper around an SMTP service. Umbraco detects what setting you have in your SMTP block, e.g. from, host, port etc.

My starter kit doesn't care how the email sender is configured. That is at the Umbraco level. Perhaps it is best to do a PR to Umbraco to get them to support what you are looking for?

**Comment by BlagoCuljak** [comment]
Sorry man, you are right. Getting the hang of v9.

**Comment by prjseal** [comment]
No need to apologise. I think we are all learning together here. I appreciate you taking the time to look into it and raise it though.
